### ISSUE TITLE
Aave shorts epic

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/trade-executor#297]
Todo:

- [x] tradingstrategy-ai/web3-ethereum-defi#109
- [x] tradingstrategy-ai/web3-ethereum-defi#110
- [x] tradingstrategy-ai/trade-executor#497
- [x] #311
- [x] #312
- [x] #313
- [ ] #314
- [x] #315
- [ ] #316

**Comment by hieuh25** [comment]
Will open another ticket for having short live execution support with Aave + 1delta
