### ISSUE TITLE
Python 3.12 and Pandas 2.x compatibility

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/trade-executor#689]
First upgrade to Pandas 2.x latest, needed for Python 3.12

-  [ ] Fix any tests failing because of broken `pandas_ta` 
    - fork to in-house `pandas_ta` and patch
    - .... or just move broken functions to new modules under `tradeeexecutor.utils` if easier
    - Check `pandas_ta` github for existing patches

Then prepare the codebase to fix the backwards incompatible break in Python 3.12 [datetime](https://github.com/tradingstrategy-ai/trading-strategy/blob/ecb85c89afc566aef000a0d3ed744e7e3641a1d8/tradingstrategy/utils/time.py#L65)

- All `datetime.datetime.utcnow` to `naive_utcnow`
- All `datetime.datetime.utcfromtimestamp` to `naive_utcfromtimestamp`
- All `pd.Timestamp.utcfromtimestamp(timestamp)` to `pd.Timestamp.utcfromtimestamp(timestamp).tz_localize(None)`

Needs to be manually search and replaced, imports added.

Then try Python 3.12

- [ ] Upgrade to Python 3.12
- [ ] Run tests and find further breakage
